language: python

sudo: false

python:
  - "2.7"

env:
  - TOXENV=py26-1.3.X,py27-1.3.X
  - TOXENV=py26-1.4.X,py27-1.4.X
  - TOXENV=py26-1.5.X,py27-1.5.X,py32-1.5.X,py33-1.5.X,py34-1.5.X
  - TOXENV=py27-1.6.X,py32-1.6.X,py33-1.6.X,py34-1.6.X
  - TOXENV=py27-1.7.X,py32-1.7.X,py33-1.7.X,py34-1.7.X
  - TOXENV=py27-1.8.X,py32-1.8.X,py33-1.8.X,py34-1.8.X

install:
  - pip install tox

script:
    - tox

branches:
  only:
    - master
