language: python

sudo: false

python:
  - "2.7"

env:
  - TOXENV=py27-1.8.X,py33-1.8.X,py34-1.8.X
  - TOXENV=coverage
  - TOXENV=docs

install:
  - pip install tox
  - pip install coveralls

script:
    - tox

branches:
  only:
    - master

after_success:
  - coveralls
